[W817 11:25:35.439714437 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W817 11:25:45.456492867 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
  File "/home/agipml/sourav.rout/ALL_FILES/project/mathgpt/src/train.py", line 78
    if ((step > 0 and step % self.eval_freq == 0) or self.is_last_step) and (not use_torch_compile):
    ^
IndentationError: expected an indented block after 'if' statement on line 74
  File "/home/agipml/sourav.rout/ALL_FILES/project/mathgpt/src/train.py", line 78
    if ((step > 0 and step % self.eval_freq == 0) or self.is_last_step) and (not use_torch_compile):
    ^
IndentationError: expected an indented block after 'if' statement on line 74
E0817 11:25:45.287000 2422819 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 0 (pid: 2423123) of binary: /home/agipml/sourav.rout/miniconda3/envs/gpt2/bin/python3.10
Traceback (most recent call last):
  File "/home/agipml/sourav.rout/miniconda3/envs/gpt2/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/agipml/sourav.rout/miniconda3/envs/gpt2/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 357, in wrapper
    return f(*args, **kwargs)
  File "/home/agipml/sourav.rout/miniconda3/envs/gpt2/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/agipml/sourav.rout/miniconda3/envs/gpt2/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/agipml/sourav.rout/miniconda3/envs/gpt2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 143, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/agipml/sourav.rout/miniconda3/envs/gpt2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 277, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-08-17_11:25:45
  host      : cn15-dgx.prajna.iitb.ac.in
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2423124)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-08-17_11:25:45
  host      : cn15-dgx.prajna.iitb.ac.in
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2423123)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
